"""empty message

Revision ID: 393932af25a8
Revises: 816679d7a02b
Create Date: 2022-01-14 20:09:37.241345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393932af25a8'
down_revision = '816679d7a02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_unique_constraint(None, 'videos', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
